### ISSUE TITLE
Add more city names

### ISSUE THREAD

**Issue by ghost** [Subcher/Ukraine-Mod#2]
Thank you for this mod! It would be great if you will add more city names. You can use this page for it: https://en.wikipedia.org/wiki/List_of_cities_in_Ukraine . Because I'm playing only on a large maps and there is not enough names, so I forced to add them manually to have only unique city names. I think, at least 100 names would be enough, but if it is easy for you, you could add all of them (459). Maybe you could use some scripts to automate this.

**Comment by Subcher** [comment]
LOL serioulsy... A thousand of cities ?? There is not this even in the base game... I will add them if you do a Pull Request. Sorry
